[tool.black]
line-length = 88

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-v --strict-markers"
testpaths = [
    "tests",
]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"